{
  imports = [
    ./applications.nix
    ./binja.nix
    ./coding.nix
    ./etterna.nix
    ./fish.nix
    ./ingrid.nix
    ./itgmania.nix
    ./kitty.nix
    ./neovim.nix
    ./spotify.nix
    ./tmux.nix
    ./utilities.nix
    ./virt-manager.nix
    ./vscode.nix
    ./zathura.nix
  ];
}
